---
# Grimmjow Jaegerjaquez - Sexta Espada (#6) - Weekly ZFS Build
# Relentless aggressor -- mirrors Kenpachi's role in the Espada pipeline.
# ZFS builds are heavyweight (DKMS compilation), fitting his brute-force nature.
#
# Espada Pipeline (Forgejo Actions):
#   Grimmjow      -> ZFS build orchestrator (Sexta, relentless aggressor)
#   Szayelaporro  -> CI: lint + test (Octava, the scientist)
#   Ulquiorra     -> Security scanning (Cuatro, cold logic)
#   Harribel      -> Build & push (Tres, calm and decisive)

name: "Grimmjow - ZFS Build"

on:
  schedule:
    - cron: "10 4 * * 0"  # Weekly: Sunday 04:10 UTC

jobs:
  szayelaporro:
    name: "Szayelaporro (CI)"
    uses: ./.forgejo/workflows/szayelaporro.yml

  ulquiorra:
    name: "Ulquiorra (Security)"
    uses: ./.forgejo/workflows/ulquiorra.yml

  harribel:
    name: "Harribel (ZFS Build)"
    needs: [szayelaporro, ulquiorra]
    uses: ./.forgejo/workflows/harribel.yml
    with:
      enable_zfs: true

  gate:
    name: "Gate (Summary)"
    needs: [szayelaporro, ulquiorra, harribel]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Pipeline summary
        run: |
          echo "Grimmjow ZFS Pipeline Summary"
          echo "=============================="
          echo "Szayelaporro (CI):       ${{ needs.szayelaporro.result }}"
          echo "Ulquiorra (Security):    ${{ needs.ulquiorra.result }}"
          echo "Harribel (ZFS Build):    ${{ needs.harribel.result }}"

      - name: Fail if any job failed
        if: >-
          needs.szayelaporro.result == 'failure' ||
          needs.ulquiorra.result == 'failure' ||
          needs.harribel.result == 'failure'
        run: exit 1
