---
# Tier Harribel - Tres Espada (#3) - Build & Push
# Mirrors Kyoraku (GitHub Actions). Builds with buildah, pushes to local registry.
# Calm and decisive -- executes the build with precision.

name: "Harribel - Build"

on:
  workflow_call:
    inputs:
      enable_zfs:
        description: "Enable ZFS kernel module build"
        type: boolean
        default: false

env:
  LOCAL_REGISTRY: localhost:5000
  IMAGE_NAME: exousia

jobs:
  build:
    name: Build Bootc Image
    runs-on: self-hosted
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync

      - name: Resolve build configuration
        run: uv run python tools/resolve_build_config.py
        env:
          INPUT_IMAGE_TYPE: fedora-sway-atomic
          INPUT_DISTRO_VERSION: "43"
          INPUT_ENABLE_PLYMOUTH: "true"
          INPUT_ENABLE_ZFS: "${{ inputs.enable_zfs }}"

      - name: Download generated Containerfile
        uses: actions/download-artifact@v4
        with:
          name: containerfile-generated

      - name: Generate image tag
        id: tag
        run: |
          SHORT_SHA=$(echo "${{ gitea.sha }}" | cut -c1-8)
          TAG="fedora-sway-atomic-${SHORT_SHA}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build with buildah
        run: |
          buildah build \
            --format oci \
            --layers \
            --build-arg FEDORA_VERSION=43 \
            --build-arg IMAGE_TYPE=fedora-sway-atomic \
            --build-arg ENABLE_PLYMOUTH=true \
            --build-arg ENABLE_ZFS=${{ inputs.enable_zfs || 'false' }} \
            -t ${{ env.LOCAL_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} \
            -f Dockerfile.generated .

      - name: Tag latest and current
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        run: |
          IMAGE="${{ env.LOCAL_REGISTRY }}/${{ env.IMAGE_NAME }}"
          buildah tag "${IMAGE}:${{ steps.tag.outputs.tag }}" "${IMAGE}:latest"
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            ROLLING_TAG="rolling-$(date -u +%Y%m%d-%H%M)"
            buildah tag "${IMAGE}:${{ steps.tag.outputs.tag }}" "${IMAGE}:${ROLLING_TAG}"
            buildah tag "${IMAGE}:${{ steps.tag.outputs.tag }}" "${IMAGE}:current"
          fi
          if [[ "${{ inputs.enable_zfs }}" == "true" ]]; then
            ZFS_TAG="zfs-$(date -u +%Y%m%d)"
            buildah tag "${IMAGE}:${{ steps.tag.outputs.tag }}" "${IMAGE}:${ZFS_TAG}"
            buildah tag "${IMAGE}:${{ steps.tag.outputs.tag }}" "${IMAGE}:zfs-latest"
          fi

      - name: Push to local registry
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        run: |
          IMAGE="${{ env.LOCAL_REGISTRY }}/${{ env.IMAGE_NAME }}"
          buildah push --tls-verify=false "${IMAGE}:${{ steps.tag.outputs.tag }}"
          buildah push --tls-verify=false "${IMAGE}:latest"
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            ROLLING_TAG="rolling-$(date -u +%Y%m%d-%H%M)"
            buildah push --tls-verify=false "${IMAGE}:${ROLLING_TAG}"
            buildah push --tls-verify=false "${IMAGE}:current"
          fi
          if [[ "${{ inputs.enable_zfs }}" == "true" ]]; then
            ZFS_TAG="zfs-$(date -u +%Y%m%d)"
            buildah push --tls-verify=false "${IMAGE}:${ZFS_TAG}"
            buildah push --tls-verify=false "${IMAGE}:zfs-latest"
          fi

      - name: Build summary
        if: always()
        run: |
          echo "Harribel: Build Results"
          echo "======================="
          echo "Image: ${{ env.LOCAL_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}"
          echo "Registry: ${{ env.LOCAL_REGISTRY }}"
          echo "Pushed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
