---
# Szayelaporro Granz - Octava Espada (#8) - CI
# Mirrors Mayuri (GitHub Actions). Runs linting and tests.
# The scientist -- methodical analysis of code quality.

name: "Szayelaporro - CI"

on:
  workflow_call:

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --dev

      - name: Ruff
        run: uv run ruff check tools/

      - name: Black (check)
        run: uv run black --check tools/

      - name: isort (check)
        run: uv run isort --check-only tools/

      - name: Pytest with coverage
        run: |
          uv run pytest tools/ -v --tb=short \
            --cov=tools --cov-branch \
            --cov-report=term
