---
# Ulquiorra Cifer - Cuatro Espada (#4) - Security
# Mirrors Byakuya (GitHub Actions). Validates structure, generates Containerfile,
# runs Hadolint + Bandit.
# Cold logic -- methodical security analysis.

name: "Ulquiorra - Security"

on:
  workflow_call:

jobs:
  security-scan:
    name: Security & Static Analysis
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required file structure
        run: |
          for file in sway.desktop environment start-sway; do
            if [ ! -f "overlays/sway/session/$file" ]; then
              echo "ERROR: Missing overlays/sway/session/$file"
              exit 1
            fi
          done

          for dir in window-managers common; do
            if [ ! -d "overlays/base/packages/$dir" ]; then
              echo "ERROR: Missing overlays/base/packages/$dir directory"
              exit 1
            fi
          done

          for script in setup-plymouth-theme dracut-rebuild; do
            if [ ! -f "overlays/sway/scripts/setup/$script" ]; then
              echo "ERROR: Missing overlays/sway/scripts/setup/$script"
              exit 1
            fi
          done

          echo "All required files present"

      - name: Transpile YAML blueprint
        id: transpile
        uses: ./.github/actions/transpile

      - name: Hadolint
        run: |
          podman run --rm -i docker.io/hadolint/hadolint \
            hadolint --ignore DL3041 --ignore DL3059 --ignore DL4006 --ignore SC3040 \
            - < Dockerfile.generated

      - name: Upload generated Containerfile
        uses: actions/upload-artifact@v4
        with:
          name: containerfile-generated
          path: Dockerfile.generated
          retention-days: 1

      - name: Bandit (Python SAST)
        run: uv run bandit -r tools/ -ll -c pyproject.toml
