# AIDE Configuration for Exousia

# The location of the database to be read.
database=file:/var/lib/aide/aide.db.gz

# The location of the database to be written.
# Setting this to the same as 'database' allows 'aide --init' to
# write directly to the final path.
database_out=file:/var/lib/aide/aide.db.gz

# Whether to gzip the output to database_out.
gzip_dbout=yes

# Default rules
# R: p+i+n+u+g+s+m+c+md5
# L: p+i+n+u+g
# E: Empty group
# >: Growing logfile p+u+g+i+n+S
# ALLXTRAHASHES: sha1+rmd160+sha256+sha512+tiger+crc32+haval+gost+adler32
# EVERYTHING: p+i+n+u+g+s+m+c+atime+ctime+mtime+md5+sha1+rmd160+sha256+sha512+tiger+crc32+haval+gost+adler32+bsize+xattrs+acl

# Custom groups
CONTENT = p+i+n+u+g+s+m+c+sha256+sha512+xattrs+acl
CONTENT_EX = p+i+n+u+g+s+m+c+sha256+sha512+xattrs+acl+atime
DATAONLY =  p+n+u+g+s+sha256+sha512+xattrs+acl

# Directories to monitor
/boot   CONTENT
/bin    CONTENT
/sbin   CONTENT
/lib    CONTENT
/lib64  CONTENT
/opt    CONTENT
/usr    CONTENT
/etc    CONTENT

# Config files
!/etc/mtab
!/etc/.*~
!/etc/aide.db.*

# Ignore transient data
!/var/log/.*
!/var/run/.*
!/var/spool/.*
!/var/cache/.*
!/var/lib/dnf/.*
!/var/lib/aide/aide.db.*
!/var/tmp/.*
!/tmp/.*

# Home directories (optional, monitoring skeleton)
/etc/skel CONTENT
