"""PR auto-review workflow — multi-model code review on Forgejo PRs."""

from datetime import timedelta

from temporalio import workflow

with workflow.unsafe.imports_passed_through():
    from src.activities.llm import Agent, AgentResponse, AgentTask, LLMActivities
    from src.activities.operations import OperationsActivities


@workflow.defn
class PRReviewWorkflow:
    """Auto-review open PRs using local LLMs.

    Schedule: every 30 min (or trigger via webhook)
        spec=ScheduleSpec(cron_expressions=["*/30 * * * *"])
    """

    @workflow.run
    async def run(self) -> dict:
        ops = OperationsActivities()
        llm = LLMActivities.__new__(LLMActivities)
        reviewed = 0

        # 1. Get open PRs
        prs = await workflow.execute_activity_method(
            ops.get_open_prs,
            start_to_close_timeout=timedelta(seconds=30),
        )

        for pr in prs:
            # 2. Get diff
            diff = await workflow.execute_activity_method(
                ops.get_pr_diff,
                pr["number"],
                start_to_close_timeout=timedelta(seconds=30),
            )

            if not diff or len(diff) < 50:
                continue

            # 3. Fast scan with small model
            scan_task = AgentTask(
                agent=Agent.OLLAMA,
                system="You are a code reviewer. Identify bugs, security issues, and style problems. Be concise. If the code looks good, say 'LGTM'.",
                prompt=f"Review this PR diff:\n\n```diff\n{diff[:4000]}\n```",
                temperature=0.2,
                max_tokens=500,
            )

            review: AgentResponse = await workflow.execute_activity_method(
                llm.dispatch_ollama,
                scan_task,
                start_to_close_timeout=timedelta(seconds=120),
            )

            # 4. Post review comment
            comment = f"## Automated Review (llama3.2)\n\n{review.content}\n\n---\n*Generated by Temporal PRReviewWorkflow*"
            await workflow.execute_activity_method(
                ops.post_pr_comment,
                args=[pr["number"], comment],
                start_to_close_timeout=timedelta(seconds=15),
            )
            reviewed += 1

        return {"reviewed": reviewed, "total_prs": len(prs)}
