# Common Base Packages
# These packages are installed regardless of desktop environment or window manager choice

metadata:
  name: base
  type: common
  description: Base packages for all Exousia builds

# Core utilities
core_utilities:
  - neovim
  - flatpak
  - rtkit
  - gnome-disk-utility
  - cargo
  - git
  - htop
  - btop
  - etckeeper
  - fastfetch
  - glances
  - kubectl
  - curl
  - iptables-nft  # Modern replacement for iptables on Fedora
  - container-selinux
  - policycoreutils-python-utils
  - cryptsetup
  - python3

# Audio and media
audio_media:
  - mpd
  - ranger

# Development and power user tools
development:
  - chezmoi
  - bat
  - wf-recorder
  - lsd
  - fzf
  - direnv
  - distrobox
  - wireguard-tools
  - ripgrep
  - zoxide
  - meson
  - ninja-build
  - pkg-config
  - rust
  - wayland-devel
  - wayland-protocols-devel
  - libxkbcommon-devel

# Virtualization
virtualization:
  - virt-manager
  - qemu-kvm
  - libvirt

# Security
security:
  - pam-u2f
  - pamu2fcfg
  - lynis
  - openssl

# Shell and terminal enhancements
shell:
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# Extra utilities
extra:
  - cava
