# Declare /var paths created by RPM packages so bootc container lint
# does not flag them as missing tmpfiles.d entries.
#
# greetd portal override (installed by ensure-sway-session)
L /var/lib/greetd/.config/systemd/user/xdg-desktop-portal.service - - - - /dev/null

# libvirt cache directories (libvirt package)
d /var/cache/libvirt 0711 root root - -
d /var/cache/libvirt/qemu 0750 root root - -

# mock build cache (mock package)
d /var/cache/mock 0775 root mock - -

# powertop calibration data (powertop package)
d /var/cache/powertop 0755 root root - -
