name: Fedora Sericea Bootc DevSec CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Nightly build at 3 AM UTC

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  security-events: write

concurrency:
  group: devsec-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/exousia

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_BASE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=ref,event=branch
            type=schedule,pattern=nightly
          labels: |
            org.opencontainers.image.licenses=MIT

      - name: Create auth.json for bootc
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p ./bootc-secrets
          AUTH_SECRET=$(echo -n "${{ github.actor }}:${{ secrets.GHCR_PAT }}" | base64 -w 0)
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$AUTH_SECRET\"}}}" > ./bootc-secrets/auth.json

      - name: Build image with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_BASE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Containerfile
          oci: false
          tls-verify: true

      - name: Lint Containerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          ignore: DL3041,DL3059,SC2086,DL4006,SC3037

      - name: Setup Bats
        id: bats_setup
        uses: bats-core/bats-action@3.0.0

      - name: Run Bats Tests
        env:
          BATS_LIB_PATH: ${{ steps.bats_setup.outputs.libpath }}
          ALL_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          # Use the first tag generated by the metadata action.
          TEST_IMAGE_TAG=$(echo "$ALL_TAGS" | head -n1)
          # Pass env vars directly to the unshare command to ensure they are available in the new user namespace.
          BATS_LIB_PATH="${BATS_LIB_PATH}" TEST_IMAGE_TAG="${TEST_IMAGE_TAG}" \
          buildah unshare -- bats -r tests
          
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Save image for subsequent jobs
        run: |
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          podman save -o image.tar "$FIRST_TAG"

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar
          retention-days: 1

  scan:
    name: Scan
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-v2

      - name: Install Trivy
        run: |
          curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.52.2/trivy_0.52.2_Linux-64bit.tar.gz \
            | tar -xz -C /usr/local/bin trivy

      - name: Trivy scan (non-blocking)
        continue-on-error: true
        run: |
          trivy image --input image.tar \
            --scanners vuln \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --format table || echo "::warning::Trivy found CRITICAL or HIGH vulnerabilities."

      - name: Semgrep static analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

  push:
    name: Push
    needs: [build, scan]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      digest: ${{ steps.push-to-registry.outputs.digest }}

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
      
      - name: Load image from tarball
        run: podman load -i image.tar

      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push image to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_BASE }}
          tags: ${{ needs.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}

  sign:
    name: Sign
    needs: push
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign the container image
        run: |
          echo "Signing image by digest: ${{ needs.push.outputs.digest }}"
          cosign sign --yes "${{ env.IMAGE_BASE }}@${{ needs.push.outputs.digest }}"
        env:
          COSIGN_EXPERIMENTAL: "true"

