name: Fedora Sericea Bootc DevSec CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Nightly build at 3 AM UTC

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  security-events: write

concurrency:
  group: devsec-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/exousia

jobs:
  build-test-scan-push-sign:
    name: Build, Test, Scan, Push & Sign
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_BASE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=ref,event=branch
            type=schedule,pattern=nightly
          labels: |
            org.opencontainers.image.licenses=MIT

      - name: Create auth.json for bootc
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p ./bootc-secrets
          AUTH_SECRET=$(echo -n "${{ github.actor }}:${{ secrets.GHCR_PAT }}" | base64 -w 0)
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$AUTH_SECRET\"}}}" > ./bootc-secrets/auth.json

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_BASE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Containerfile
          oci: false
          tls-verify: true

      - name: Lint Containerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          ignore: DL3041,DL3059,SC2086,DL4006,SC3037

      - name: Setup Bats
        id: bats_setup
        uses: bats-core/bats-action@3.0.0

      - name: Run Bats Tests
        env:
          BATS_LIB_PATH: ${{ steps.bats_setup.outputs.libpath }}
          ALL_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          TEST_IMAGE_TAG=$(echo "$ALL_TAGS" | head -n1)
          BATS_LIB_PATH="${BATS_LIB_PATH}" TEST_IMAGE_TAG="${TEST_IMAGE_TAG}" \
          buildah unshare -- bats -r tests

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-v2

      - name: Install Trivy
        run: |
          curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.52.2/trivy_0.52.2_Linux-64bit.tar.gz \
            | tar -xz -C /usr/local/bin trivy

      - name: Trivy scan (non-blocking)
        continue-on-error: true
        run: |
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          trivy image "$FIRST_TAG" \
            --scanners vuln \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --format table || echo "::warning::Trivy found CRITICAL or HIGH vulnerabilities."

      - name: Semgrep static analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Push image to registry
        if: github.event_name != 'pull_request'
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_BASE }}
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign the container image
        if: github.event_name != 'pull_request'
        run: |
          echo "Signing image by digest: ${{ steps.push-to-registry.outputs.digest }}"
          cosign sign --yes "${{ env.IMAGE_BASE }}@${{ steps.push-to-registry.outputs.digest }}"
        env:
          COSIGN_EXPERIMENTAL: "true"

