name: Fedora Sericea Bootc DevSec CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *" # Nightly build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: borninthedark/exousia

jobs:
  build-scan-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=sha
            type=schedule,pattern=nightly

      # Build image (does NOT push)
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Containerfile
          build-args: |
            GH_USER=${{ github.actor }}
            GH_TOKEN=${{ secrets.GHCR_PAT }}

      # Push image to GHCR using GHCR_PAT
      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
